print("Hello World!")
print("My name is Marco Luis Coros.")
print("You can call me Marco.")
print("I am a Computer Engineering Student currently studying in Ateneo de Manila University.")
print("testing this right now June 23 2022")